[[exercise]]
name = "Back Squat"
description = "Full depth barbell back squat"
primary_muscle = "Quadriceps"

[[exercise]]
name = "Bench Press"
description = "Flat bench barbell press"
primary_muscle = "Chest"

[[exercise]]
name = "Incline Bench Press"
description = "Incline bench barbell press"
primary_muscle = "Chest"

[[exercise]]
name = "Close-Grip Bench Press"
description = "Close grip bench barbell press"
primary_muscle = "Chest"

[[exercise]]
name = "Deadlift"
description = "Conventional barbell deadlift"
primary_muscle = "Posterior Chain"
