name = "Sexy program"
description = "Just a test ma man"

[[blocks]]
name = "Heavy Day"
description = "Max effort day"

[[blocks.exercises]]
name = "Back Squat"
sets = 3
reps = ["5", "6-10", "AMRAP"]
target_rpe = 8.0
notes = "Work up to heavy set"

[[blocks.exercises]]
name = "Bench Press"
sets = 3
reps = ["5", "5", "5"]
target_rm_percent = 0.75
