name = "Program 3"
description = "Just a test ma man"

[[blocks]]
name = "Sexo day"
description = "Max effort day"

[[blocks.exercises]]
name = "Back Squat"
sets = 3
reps = ["5", "6-10", "15"]
target_rpe = [8.0, 9.0, 10.0]
notes = "Work up to heavy set"
program_1rm = 150.0
technique = "superset"    # Mark this exercise as part of a superset
group = 1                 # Group 1

[[blocks.exercises]]
name = "Bench Press"
sets = 3
reps = ["5", "5", "5"]
target_rm_percent = [95.0, 75.0, 85.0]
program_1rm = 110.0
options = ["Incline Bench Press", "Close-Grip Bench Press"]
technique = "superset"    # Mark this exercise as part of a superset
group = 1                 # Group 1

[[blocks.exercises]]
name = "Incline Bench Press"
sets = 3
reps = ["5", "5", "5"]
target_rm_percent = [95.0, 75.0, 85.0]
program_1rm = 110.0
options = ["Close-Grip Bench Press"]
technique = "myoreps"

[[blocks.exercises]]
name = "Close-Grip Bench Press"
sets = 3
reps = ["15-20"]
# program_1rm = 110.0
technique = "hell"
